### ISSUE TITLE
mpsc-queue.hpp has issue

### ISSUE THREAD

**Issue by X-Ryl669** [chronoxor/CppBenchmark#1]
When using std::aligned_storage, you must explicitly call constructor and destructors on the "reinterpreted_cast"'d object (with placement new, and explicit output->~T() call).

In all case, std::aligned_storage is not required in this file, since the compiler will ensure that the structure is correctly aligned anyway.
By default, unless you pragma pack your structure (which is not the case here), the compiler will ensure the structure is aligned with respect to its largest field's alignment requirement, and that's exactly what you get with the std::aligned_storage code that's written.

**Comment by chronoxor** [comment]
You are right. I've performed some experiments with std::aligned_storage and found that it's useless in my cases and don't influence on wait-free queues' performance. I've committed necessary fixes. Thank you for assistance!
