### ISSUE TITLE
The sort example kinda does not make sense

### ISSUE THREAD

**Issue by TheMates** [chronoxor/CppBenchmark#10]
I am browsing the examples and putting things together, and noticed, that the sort example does not really make sense.

Each sort class inheriting from the SortFixture calls Initialize at the beginning of an attempt, which populates the items, but then in each Run called during an attempt, the items are not changed. So the first Run sorts the items and then every subsequent run has the items already sorted.

**Comment by chronoxor** [comment]
Thanks for pointing on it! Fixed
