### ISSUE TITLE
fatal error: benchmark/cppbenchmark.h: No such file or directory

### ISSUE THREAD

**Issue by Aniburner** [chronoxor/CppBenchmark#5]
I build CppBenchmark library and put libcppbenchmark.a into /usr/lib/, then I try to compile serialize.cpp with flag -lcppbenchmark under FastBinaryEncoding/performance/, but it turns out an error like this: 
serialize.cpp:5:10: fatal error: benchmark/cppbenchmark.h: No such file or directory
    5 | #include "benchmark/cppbenchmark.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
What should I do?

**Comment by chronoxor** [comment]
You need to provide "-I /path/to/cppbenchmark/include" option.
https://www.rapidtables.com/code/linux/gcc/gcc-i.html
